### ISSUE TITLE
The `provider/handler.ts` file is not included in the npm package

### ISSUE THREAD

**Issue by miensol** [pepperize/cdk-ses-smtp-credentials#129]
I think the library should include the `provider/*.ts` files so that the bundler on the installation site can do it's work.

```
node_modules/aws-cdk-lib/aws-lambda-nodejs/lib/function.ts:116
      throw new Error(`Cannot find entry file at ${entry}`);
            ^
Error: Cannot find entry file at ./node_modules/@pepperize/cdk-ses-smtp-credentials/lib/provider/handler.ts
    at findEntry (/Users/piotr/dev/practi-reportportal/node_modules/aws-cdk-lib/aws-lambda-nodejs/lib/function.ts:116:13)
    at new NodejsFunction (./node_modules/aws-cdk-lib/aws-lambda-nodejs/lib/function.ts:43:32)
    at new SesSmtpCredentialsProvider (./node_modules/@pepperize/cdk-ses-smtp-credentials/src/ses-smtp-credentials-provider.ts:25:21)
    at new SesSmtpCredentials (./node_modules/@pepperize/cdk-ses-smtp-credentials/src/ses-smtp-credentials.ts:43:30)
```

**Comment by pflorek** [comment]
@miensol thank you! can you give an example of the usage please
